CREATE TABLE IF NOT EXISTS faturacao_registos (
    numero VARCHAR(30) PRIMARY KEY,
    ano INT NULL,
    origem VARCHAR(30) NULL,
    orcamento_numero VARCHAR(30) NULL,
    encomenda_numero VARCHAR(30) NULL,
    cliente_codigo VARCHAR(20) NULL,
    cliente_nome VARCHAR(150) NULL,
    data_venda DATE NULL,
    data_vencimento DATE NULL,
    valor_venda_manual DECIMAL(12,2) NULL,
    estado_pagamento_manual VARCHAR(30) NULL,
    obs TEXT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL
);

CREATE TABLE IF NOT EXISTS faturacao_faturas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    registo_numero VARCHAR(30) NOT NULL,
    documento_id VARCHAR(60) NULL,
    doc_type VARCHAR(10) NULL,
    numero_fatura VARCHAR(60) NULL,
    serie VARCHAR(40) NULL,
    serie_id VARCHAR(40) NULL,
    seq_num INT NULL,
    at_validation_code VARCHAR(40) NULL,
    atcud VARCHAR(80) NULL,
    guia_numero VARCHAR(30) NULL,
    data_emissao DATE NULL,
    data_vencimento DATE NULL,
    moeda VARCHAR(10) NULL,
    iva_perc DECIMAL(6,2) NULL,
    subtotal DECIMAL(12,2) NULL,
    valor_iva DECIMAL(12,2) NULL,
    valor_total DECIMAL(12,2) NULL,
    caminho VARCHAR(512) NULL,
    obs TEXT NULL,
    estado VARCHAR(30) NULL,
    anulada TINYINT(1) NULL DEFAULT 0,
    anulada_motivo TEXT NULL,
    anulada_at DATETIME NULL,
    legal_invoice_no VARCHAR(80) NULL,
    system_entry_date DATETIME NULL,
    source_id VARCHAR(80) NULL,
    source_billing VARCHAR(1) NULL,
    status_source_id VARCHAR(80) NULL,
    hash VARCHAR(512) NULL,
    hash_control VARCHAR(80) NULL,
    previous_hash VARCHAR(512) NULL,
    document_snapshot_json LONGTEXT NULL,
    communication_status VARCHAR(30) NULL,
    communication_filename VARCHAR(255) NULL,
    communication_error TEXT NULL,
    communicated_at DATETIME NULL,
    communication_batch_id VARCHAR(80) NULL,
    created_at DATETIME NULL,
    INDEX idx_fat_faturas_reg (registo_numero),
    INDEX idx_fat_faturas_doc (documento_id),
    INDEX idx_fat_faturas_emissao (data_emissao),
    INDEX idx_fat_faturas_serie_seq (serie_id, seq_num),
    INDEX idx_fat_faturas_legal (legal_invoice_no),
    INDEX idx_fat_faturas_comm (communication_status),
    CONSTRAINT fk_fat_faturas_reg FOREIGN KEY (registo_numero) REFERENCES faturacao_registos(numero) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS faturacao_pagamentos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    registo_numero VARCHAR(30) NOT NULL,
    pagamento_id VARCHAR(60) NULL,
    fatura_documento_id VARCHAR(60) NULL,
    data_pagamento DATE NULL,
    valor DECIMAL(12,2) NULL,
    metodo VARCHAR(40) NULL,
    referencia VARCHAR(120) NULL,
    titulo_comprovativo VARCHAR(150) NULL,
    caminho_comprovativo VARCHAR(512) NULL,
    obs TEXT NULL,
    created_at DATETIME NULL,
    INDEX idx_fat_pag_reg (registo_numero),
    INDEX idx_fat_pag_fatura (fatura_documento_id),
    INDEX idx_fat_pag_data (data_pagamento),
    CONSTRAINT fk_fat_pag_reg FOREIGN KEY (registo_numero) REFERENCES faturacao_registos(numero) ON DELETE CASCADE
);
